import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {createServer} from '../src/server.mjs';
const dataPath=new URL('../.runtime/incidents.json',import.meta.url);
const listen=server=>new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const close=server=>new Promise(resolve=>server.close(resolve));
const priority={critical:4,high:3,medium:2,low:1};
function expected(p){return records.filter(r=>(!p.get('q')||[r.id,r.title,r.description].some(v=>v.toLowerCase().includes(p.get('q').toLowerCase())))&&['service','severity','status'].every(k=>!p.getAll(k).length||p.getAll(k).includes(r[k]))&&(!p.get('from')||r.openedAt.slice(0,10)>=p.get('from'))&&(!p.get('to')||r.openedAt.slice(0,10)<=p.get('to'))).sort((a,b)=>((p.get('sort')==='severity'?priority[a.severity]-priority[b.severity]:a.openedAt.localeCompare(b.openedAt))*(p.get('direction')==='asc'?1:-1))||a.id.localeCompare(b.id));}
const original=await readFile(dataPath),records=JSON.parse(original);
function parseCSV(text){const rows=[];let row=[],value='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else if(c==='\r'&&!quoted&&text[i+1]==='\n'){row.push(value);rows.push(row);row=[];value='';i++;}else value+=c;}return rows;}
test('actual HTTP: literal queries, combinations, stable sorting, pages, summaries, details and CSV',async()=>{const server=await createServer();await listen(server);const base=`http://127.0.0.1:${server.address().port}`;try{for(const qs of ['', 'q=INC-000001','q=RETRY%2C','q=%3Csample%3E','q=.*','service=Billing&service=Search&severity=high&severity=critical&status=open&from=2026-04-10&to=2026-04-20','from=2026-04-01&to=2026-04-01','sort=severity&direction=desc','sort=severity&direction=asc','sort=openedAt&direction=asc','page=2&size=50']){const p=new URLSearchParams(qs),all=expected(p),r=await fetch(base+'/api/incidents?'+p),body=await r.json();assert.equal(r.status,200);assert.equal(body.total,all.length);assert.equal(body.unresolved,all.filter(r=>r.status!=='resolved').length);assert.equal(body.high,all.filter(r=>priority[r.severity]>=3).length);const days={};for(const r of all)days[r.openedAt.slice(0,10)]=(days[r.openedAt.slice(0,10)]||0)+1;assert.deepEqual(body.days,Object.entries(days).sort());const size=p.get('size')==='50'?50:25;assert.deepEqual(body.rows,all.slice((body.page-1)*size,body.page*size));assert.deepEqual(await(await fetch(base+'/api/incidents?'+p)).json(),body);const csv=parseCSV(await(await fetch(base+'/api/export?'+p)).text());assert.deepEqual(csv[0],Object.keys(records[0]));assert.equal(csv.length,all.length+1);for(let i=0;i<all.length;i++)assert.deepEqual(csv[i+1],csv[0].map(k=>k==='tags'?JSON.stringify(all[i][k]):String(all[i][k]??'')));}assert.deepEqual(await(await fetch(base+'/api/incidents/INC-000001')).json(),records[0]);assert.equal((await fetch(base+'/api/incidents/missing')).status,404);}finally{await close(server);assert.deepEqual(await readFile(dataPath),original);}});
test('real sandbox Chromium: results, keyboard, views, details, export, responsive, loading and genuine failure/retry',async()=>{
const alias=execFileSync('bash',['-c','command -v qualification-chromium'],{encoding:'utf8'}).trim(),tool=path.dirname(alias);process.env.PLAYWRIGHT_BROWSERS_PATH=path.resolve(tool,'../browsers');await mkdir('.runtime/browser-tmp',{recursive:true});const {chromium}=await import('playwright');let browser,server=await createServer();await listen(server);const port=server.address().port,base=`http://127.0.0.1:${port}`;try{browser=await chromium.launch({channel:'chromium',headless:true,chromiumSandbox:true,env:{...process.env,LD_LIBRARY_PATH:path.resolve(tool,'../host-libs/usr/lib/x86_64-linux-gnu'),ALSA_CONFIG_PATH:path.resolve(tool,'../host-libs/usr/share/alsa/alsa.conf'),TMPDIR:'.runtime/browser-tmp',TMP:'.runtime/browser-tmp',TEMP:'.runtime/browser-tmp'}});const page=await browser.newPage();await page.goto(base);await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===25);assert.equal(await page.locator('.metric strong').first().textContent(),'2400');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.name),'q');assert.notEqual(await page.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle),'none');await page.getByLabel('Search incidents').fill('INC-000001');await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===1);await page.getByRole('button',{name:'INC-000001',exact:true}).focus();await page.keyboard.press('Enter');await page.locator('#detail:not([hidden])').waitFor();assert.equal(await page.locator('#fields dt').count(),11);assert.ok((await page.locator('#fields').textContent()).includes('<sample>'));assert.equal(await page.locator('#fields sample').count(),0);await page.getByRole('button',{name:'Back to results'}).focus();await page.keyboard.press('Enter');assert.equal(await page.getByLabel('Search incidents').inputValue(),'INC-000001');await page.getByLabel('View name',{exact:true}).fill('Literal incident');await page.getByRole('button',{name:'Save view',exact:true}).focus();await page.keyboard.press('Enter');await page.reload();await page.getByLabel('Saved views',{exact:true}).selectOption('Literal incident');await page.getByRole('button',{name:'Open view',exact:true}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===1);assert.equal(await page.getByLabel('Search incidents').inputValue(),'INC-000001');await page.getByRole('button',{name:'Delete view',exact:true}).click();assert.equal(await page.locator('#saved option').count(),1);const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Export all as CSV'}).click();const download=await downloadPromise;await download.saveAs('.runtime/browser-export.csv');assert.equal(parseCSV(await readFile('.runtime/browser-export.csv','utf8')).length,2);
await page.getByRole('button',{name:'Clear all',exact:true}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===25);await page.getByRole('button',{name:'Next',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#page').textContent==='Page 2 of 96');await page.getByLabel('Sort by').selectOption('severity');await page.waitForFunction(()=>document.querySelector('#page').textContent==='Page 1 of 96');assert.equal(await page.locator('#rows tr td:nth-child(3)').first().textContent(),'critical');await page.getByLabel('Rows per page').selectOption('50');await page.waitForFunction(()=>document.querySelectorAll('#rows tr').length===50);await page.getByLabel('Accounts',{exact:true}).check();await page.getByLabel('Billing',{exact:true}).check();await page.getByLabel('high',{exact:true}).check();await page.getByLabel('Opened from (UTC)').fill('2026-04-01');await page.getByLabel('Opened through (UTC)').fill('2026-04-30');await page.waitForFunction(()=>!document.querySelector('#results').hasAttribute('aria-busy'));const count=Number(await page.locator('.metric strong').first().textContent());assert.ok(count>0&&count<2400);await page.getByLabel('View name',{exact:true}).fill('April');await page.getByRole('button',{name:'Save view',exact:true}).focus();await page.keyboard.press('Enter');await page.reload();await page.getByLabel('Saved views',{exact:true}).selectOption('April');await page.getByRole('button',{name:'Open view',exact:true}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>!document.querySelector('#results').hasAttribute('aria-busy'));assert.equal(await page.getByLabel('Accounts',{exact:true}).isChecked(),true);assert.equal(await page.getByLabel('Rows per page').inputValue(),'50');assert.equal(Number(await page.locator('.metric strong').first().textContent()),count);
await page.setViewportSize({width:375,height:812});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('.table-scroll').focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('.table-scroll').scrollLeft>0);await page.getByLabel('Search incidents').fill('no such incident');await page.locator('#empty:not([hidden])').waitFor();await page.screenshot({path:'.runtime/narrow-empty.png',fullPage:true});
// A real stopped backend makes the request fail; no routes or responses are mocked.
await close(server);server=null;await page.getByLabel('Search incidents').fill('retry');await page.locator('#retry:not([hidden])').waitFor();assert.equal(await page.getByLabel('Accounts',{exact:true}).isChecked(),true);assert.equal(await page.getByLabel('Search incidents').inputValue(),'retry');server=await createServer();await new Promise(resolve=>server.listen(port,'127.0.0.1',resolve));
// Pause actual server connections to observe loading before real response completion.
const pause=socket=>{socket.pause();setTimeout(()=>socket.resume(),400);};server.on('connection',pause);await page.getByRole('button',{name:'Retry',exact:true}).click();assert.equal(await page.locator('#message').textContent(),'Loading incidents…');await page.waitForFunction(()=>document.querySelector('#message').textContent==='');server.off('connection',pause);assert.equal(await page.getByLabel('Search incidents').inputValue(),'retry');await page.screenshot({path:'.runtime/narrow-results.png',fullPage:true});await writeFile('.runtime/app-browser-receipt.json',JSON.stringify({browserVersion:browser.version(),sandbox:true,journeys:['HTTP results','keyboard focus','plain text details','saved views reload/delete','CSV download','pagination/reset','filters','narrow screen','empty','loading','stopped server failure','retry'],canonicalBytesPreserved:true}));
}finally{if(browser)await browser.close();if(server)await close(server);assert.deepEqual(await readFile(dataPath),original);}
});
