const $=s=>document.querySelector(s), form=$('#filters');
const values={service:['Accounts','Billing','Search','Uploads','Notifications','Integrations'],status:['open','in_progress','resolved'],severity:['critical','high','medium','low']};
for(const [key,options] of Object.entries(values)){const field=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=key[0].toUpperCase()+key.slice(1);field.append(legend);for(const value of options){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name=key;input.value=value;label.append(input,document.createTextNode(value.replaceAll('_',' ')));field.append(label);}$('#choices').append(field);}
let page=1,pages=1,sequence=0,views=Object.create(null);
try{views=Object.assign(Object.create(null),JSON.parse(localStorage.getItem('incident-views')||'{}'));}catch{}
function params(){const p=new URLSearchParams(new FormData(form));for(const [k,v] of [...p])if(!v)p.delete(k);p.set('page',page);return p;}
function showViews(){const select=$('#saved');select.replaceChildren(new Option('Choose a view',''));for(const name of Object.keys(views))select.add(new Option(name,name));}
function persist(){localStorage.setItem('incident-views',JSON.stringify(views));showViews();}
async function json(url){const r=await fetch(url);if(!r.ok)throw Error('Request failed');return r.json();}
async function load(){const ticket=++sequence,p=params();$('#message').textContent='Loading incidents…';$('#retry').hidden=true;$('#results').setAttribute('aria-busy','true');$('#active').textContent=[...p].filter(([k])=>k!=='page').map(([k,v])=>`${k}: ${v}`).join(' · ');$('#export').href='/api/export?'+p;
try{const data=await json('/api/incidents?'+p);if(ticket!==sequence)return;page=data.page;pages=data.pages;$('#summary').replaceChildren();for(const [label,n]of [['Matching incidents',data.total],['Unresolved',data.unresolved],['Critical + high',data.high]]){const box=document.createElement('div');box.className='metric';const strong=document.createElement('strong');strong.textContent=n;box.append(strong,document.createTextNode(label));$('#summary').append(box);}$('#rows').replaceChildren();for(const r of data.rows){const tr=document.createElement('tr'),td=document.createElement('td'),button=document.createElement('button');button.textContent=r.id;button.onclick=()=>detail(r.id);const small=document.createElement('small');small.textContent=r.title;td.append(button,small);tr.append(td);for(const k of ['service','severity','status','openedAt']){const cell=document.createElement('td');cell.textContent=r[k];tr.append(cell);}$('#rows').append(tr);}$('#days').replaceChildren();const max=Math.max(1,...data.days.map(d=>d[1]));for(const [day,count]of data.days){const row=document.createElement('div');row.className='day';const date=document.createElement('span'),bar=document.createElement('span'),n=document.createElement('span');date.textContent=day;bar.className='bar';bar.style.width=`${100*count/max}%`;bar.setAttribute('aria-hidden','true');n.textContent=count;row.append(date,bar,n);$('#days').append(row);}$('#empty').hidden=!!data.total;$('#page').textContent=`Page ${page} of ${pages}`;$('#prev').disabled=page<=1;$('#next').disabled=page>=pages;$('#message').textContent='';}
catch{if(ticket===sequence){$('#message').textContent='Could not load incidents. Your selections are preserved. Retry when the server is available.';$('#retry').hidden=false;}}
finally{if(ticket===sequence)$('#results').removeAttribute('aria-busy');}}
async function detail(id){$('#message').textContent='Loading incident…';try{const r=await json('/api/incidents/'+id);$('#fields').replaceChildren();for(const[k,v]of Object.entries(r)){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=Array.isArray(v)?v.join(', '):v??'—';$('#fields').append(dt,dd);}$('#detail-title').textContent=r.id+' · '+r.title;$('#results').hidden=true;$('#detail').hidden=false;$('#detail-title').focus();$('#message').textContent='';}catch{$('#message').textContent='Could not load incident. Retry by opening it again.';}}
form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('input',()=>{page=1;load();});$('#clear').onclick=()=>{form.reset();page=1;load();};$('#retry').onclick=load;$('#prev').onclick=()=>{page--;load();};$('#next').onclick=()=>{page++;load();};$('#back').onclick=()=>{$('#detail').hidden=true;$('#results').hidden=false;$('#rows button')?.focus();};$('#save').onclick=()=>{const name=$('#view-name').value.trim();if(!name){$('#view-name').focus();return;}views[name]=[...params()].filter(([k])=>k!=='page');persist();$('#saved').value=name;};$('#open-view').onclick=()=>{const entries=views[$('#saved').value];if(!entries)return;form.reset();for(const input of form.elements){if(!input.name)continue;const matches=entries.filter(([k])=>k===input.name).map(([,v])=>v);if(input.type==='checkbox')input.checked=matches.includes(input.value);else if(matches.length)input.value=matches[0];}page=1;load();};$('#delete-view').onclick=()=>{delete views[$('#saved').value];persist();};showViews();load();
